### PR TITLE
Updated README information

### PR DESCRIPTION
**Pull request by Klairm**
Updated validating flash dumps link

### CODE REVIEW

**Review by littlebalup — CHANGES_REQUESTED** [review]
why not "http://www.psdevwiki.com/ps3/Validating_flash_dumps" only ?
We don't need a web.archive.org link

**Review by Klairm — COMMENTED** [review]
Updated link

**Comment by Swizzy** [comment]
It's rather pointless at this point seeing as it doesn't change anything, however - we should request that the web archive archives the current state of the wiki page for future reference if the site goes down again

**Comment by Swizzy** [comment]
Oops, i was too fast - it changed... i'll merge it with working version :)

**Review by Swizzy — APPROVED** [review]

**Pull request merged**
